apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-express-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-express
  template:
    metadata:
      labels:
        app: hello-express
    spec:
      containers:
        - name: hello-express
          image: <your-dockerhub-username>/hello-express:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-express-service
spec:
  selector:
    app: hello-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
